project_id = "nalhlfmfxrwsvruspbdw"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54328
site_url = "https://samaritan-hub.lovable.app"
additional_redirect_urls = [
  "https://samaritan-hub.lovable.app",
  "https://id-preview--5c2c5d0a-3ca3-46cb-9dc3-634b2e2303e2.lovable.app",
  "https://5c2c5d0a-3ca3-46cb-9dc3-634b2e2303e2.sandbox.lovable.dev"
]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_manual_linking = false

[auth.email]
enable_signup = false
double_confirm_changes = true
enable_confirmations = false
secure_password_change = true

[auth.email.smtp]
# Email settings would be configured here if needed

[functions.send-email-msgraph]
verify_jwt = true

[functions.get-user-profile]
verify_jwt = true

[functions.notify-intake-submission]
verify_jwt = false