// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nalhlfmfxrwsvruspbdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hbGhsZm1meHJ3c3ZydXNwYmR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNDA4MDcsImV4cCI6MjA3MjYxNjgwN30.dyPRxZ_QlD-WHbup9dDpiVBXv4_aKhogAjQg8_OMJco";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});